CREATE TABLE customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(500) NOT NULL,
    telefon_number VARCHAR(50),
    email VARCHAR(500) UNIQUE NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO customer (name, telefon_number, email)
VALUES
    ('Zara Larsson', '0701234567', 'zara@larsson.se'),
    ('Molly Sandén', '0707654321', 'molly@sanden.se'),
    ('Veronica Maggio', '0709871234', 'veronica@maggio.se');