CREATE TABLE customer (
    id  bigint generated by default as identity primary key,
    name    VARCHAR(500) NOT NULL,
    email   VARCHAR(500) UNIQUE NOT NULL,
    timestamp   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO customer (name, email)
VALUES ('Zara Larsson','zara@larsson.se'),
       ('Molly Sandén','molly@sanden.se'),
       ('Veronica Maggio','veronica@maggio.se');