CREATE TABLE products
(
    id            bigint generated by default as identity
        primary key,
    name          varchar(300),
    category      varchar(300),
    price         integer,
    stockquantity integer
);

INSERT INTO products
    (name, category, price, stockquantity)
VALUES ('Macbook Air', 'Laptop', 9999, 10),
       ('Samsung OLED', 'TV', 11999, 8),
       ('iPhone 15', 'Phone', 8999, 13);