CREATE TABLE reviews
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name  VARCHAR(255)                            NOT NULL,
    rating        INTEGER CHECK (rating BETWEEN 0 AND 10) NOT NULL,
    comment       VARCHAR(1000),
    review_date   DATE,
    reviewer_name VARCHAR(255)
);

INSERT INTO review (id, product_name, rating, comment, review_date, reviewer_name)
VALUES ('1', 'Samsung Galaxy S23 Ultra', '9',
        'The camera quality is outstanding, especially in low light. The display is bright and smooth, and overall performance feels incredibly fast.',
        '2026-01-01', 'Psy'),
       ('2', 'LG UltraGear 27GP850 Gaming Monitor', '8',
        'Great color accuracy and a very responsive 165Hz panel. Perfect for gaming and productivity, though the stand could be a bit sturdier.',
        '2026-01-25', 'Jungkook'),
       ('3', 'Hyundai Portable SSD', '7',
        'Fast transfer speeds and a compact design make it easy to carry around. It gets slightly warm during heavy use, but nothing too serious.',
        '2026-02-12', 'G-Dragon');