/* Table creation */
CREATE TABLE Suppliers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    companyName   VARCHAR(255) NOT NULL,
    country       VARCHAR(255) NOT NULL,
    contactPerson VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL
);

/* Sample data insertion */
INSERT INTO Suppliers (companyName, country, contactPerson, email)
VALUES ('Global Tech Supplies', 'USA', 'John Doe', 'john.doe@globaltech.com'),
       ('Euro Electronics', 'Germany', 'Anna Schmidt', 'anna.schmidt@electronics.com');